{% set name = "opensearch-py" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opensearch-py-{{ version }}.tar.gz
  sha256: 493b224d0f865f62663f689c3a7662b1edccf9ee6c7643f2561cafda04e3a66a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - certifi
    - python >=3.6,<4.0
    - urllib3 >=1.21.1,<2
    - requests >=2.4.0,<3.0.0
    - six
    - python-dateutil
  run_constrained:
    - aiohttp >=3,<4

test:
  imports:
    - opensearchpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opensearch-project/opensearch-py
  summary: Python low-level client for OpenSearch
  doc_url: https://opensearch.org/docs/latest/clients/python/
  dev_url: https://github.com/opensearch-project/opensearch-py
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisburr
